# Generated by Django 5.0.13 on 2025-12-03 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('sitio_web', models.CharField(max_length=255)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidor', models.CharField(max_length=100)),
                ('contacto_principal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion_almacen', models.CharField(max_length=255)),
                ('pais_distribucion', models.CharField(max_length=50)),
                ('tipo_distribucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidad_genero', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('es_ficcion', models.BooleanField()),
                ('epoca_popular', models.CharField(max_length=50)),
                ('publico_objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LibroEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('fecha_publicacion', models.DateField()),
                ('num_paginas', models.IntegerField()),
                ('precio_tapa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_almacen', models.IntegerField()),
                ('estado_publicacion', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=50)),
                ('autor_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.autoreditorial')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.editor')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.generoliterario')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField()),
                ('cantidad_enviada', models.IntegerField()),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.CharField(max_length=50)),
                ('fecha_recepcion_esperada', models.DateField()),
                ('numero_seguimiento', models.CharField(max_length=50)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.distribuidor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.libroeditorial')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField()),
                ('porcentaje_regalias', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_adelanto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_fin_contrato', models.DateField()),
                ('clausulas_especiales', models.TextField()),
                ('id_agente_literario', models.IntegerField()),
                ('autor_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.autoreditorial')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.libroeditorial')),
            ],
        ),
    ]
